name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions üöÄ
on:
  push:
    branches: [ demo ]
jobs:
  Generate-Apis:
    runs-on: ubuntu-latest
    steps:
      - name: Use JAVA 8 - OpenJDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run generate script
        run: ./generate_api.sh 
      - name: List files in the gen directory
        run:  ls ${{ github.workspace }}/asana/resources/gen/
      - name: List files in samples directory and echo current and worksapce directories
        run: |
          ls ${{ github.workspace }}/samples/;
          pwd;
          echo "${{ github.workspace }}"
      - run: echo "üçè This job's status is ${{ job.status }}."
